language: php

php:
    - 7.2
    - 7.3
    - 7.4

dist: bionic

branches:
    only:
        - master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - DOCKER_BUILD=false
        - SYMFONY_DEPRECATIONS_HELPER=strict

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

jobs:
    include:
        - php: 7.2
          services: [docker]
          env:
            - DOCKER_BUILD=true
            - COMPOSER_PREFER_LOWEST=true

notifications:
    email: samuel.breu@bresam.ch
